name: voxeet-uxkit-react CI

on:
  push:
    branches:
      - cicd-experiment
      - 'dev/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://stg-gke-eu.voxeet.net/nexus/repository/npm-group/'
    - name: build package
      run: |
        yarn install
        yarn build
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUS_AUTH_TOKEN }}

    - uses: rlespinasse/github-slug-action@master
    - name: yarn publish
      run: |
          echo yarn version $(npm --silent run get-version)-${{ env.GITHUB_REF_SLUG }}-${{ env.GITHUB_SHA_SHORT }}
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUS_AUTH_TOKEN }}
