name: voxeet-uxkit-react CI

on:
  push:
    branches:
      - cicd-experiment

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        SHA8: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v2
    - name: setting nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install, build
      run: |
        echo yarn install
        echo yarn build

    - uses: rlespinasse/github-slug-action@master
    - name: yarn publish
      run: |
          echo yarn version ${{ env.GITHUB_REF_SLUG }}-${{ env.GITHUB_SHA_SHORT }}
