name: voxeet-uxkit-react CI

on:
  push:
    branches:
      - cicd-experiment
      - cicd-integration

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://stg-gke-eu.voxeet.net/nexus/repository/npm-group/'
        always-auth: true
    - uses: rlespinasse/github-slug-action@master
    - name: build and publish
      run: |
          yarn version --no-git-tag-version --new-version $(npm --silent run get-version)-${{ env.GITHUB_REF_SLUG }}-${{ env.GITHUB_SHA_SHORT }}
          yarn publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUS_AUTH_TOKEN }}
