name: Release build

on:
  create:
    tags:
      - 'rel/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
        always-auth: true
    - name: install dependencies
      run: |
          yarn install
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: build and publish
      run: |
          yarn publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
